### ISSUE TITLE
Difference with plain Tor hidden service?

### ISSUE THREAD

**Issue by stokito** [theborakompanioni/ngtor#4]
Could you please explain what is a difference between the tunnel and Hidden Service of Tor itself?
As far I understood this is just a Java implementation of Tor with a simple command to make a hidden service, right?

**Comment by theborakompanioni** [comment]
> Could you please explain what is a difference between the tunnel and Hidden Service of Tor itself? As far I understood this is just a Java implementation of Tor with a simple command to make a hidden service, right?

You are completely right. It is as if you had Tor installed natively and dynamically adjusted your `torrc` file.
Comes with small benefits (spin up temporary services quite quickly; no changes to `torrc`, etc.), but also drawbacks (you are not in control of Tor version, etc.). It is just a small utility and once the `serve` command (#1) is implemented, it is considered feature complete ; -)

**Comment by stokito** [comment]
thank you for the explanation.
I remember OnionShare that also is an attempt to make a user friendly Tor
